### ISSUE TITLE
如何使用HangfireHttpJob

### ISSUE THREAD

**Issue by benxionghu** [gnsilence/HangfireHttpJob#12]
引用nuget包之后 
如何在界面中添加按钮

**Comment by gnsilence** [comment]
> 引用nuget包之后
> 如何在界面中添加按钮
可以看示例,可以在UseHangfireHttpJob的配置中配置按钮文本,要自己添加其他按钮的话,是需要修改源码的,拓展控制面板的视图页

**Comment by benxionghu** [comment]
谢谢 已经解决了
