### ISSUE TITLE
1.1.2中编辑定时任务接口

### ISSUE THREAD

**Issue by BingboLI** [gnsilence/HangfireHttpJob#18]
在定期作业页面里选中一条job点击编辑定时任务时，这个接口返回了错误，导致该功能不可用。
![image](https://user-images.githubusercontent.com/26083509/184295793-62ef7feb-0710-4f81-8cda-4af88f6db2e5.png)
在Hangfire.HttpJob.dll模块中抛出了一个Object reference not set to an instance of an object.异常
![image](https://user-images.githubusercontent.com/26083509/184296146-48514613-69cd-428c-af2e-8e760257dd7f.png)

**Comment by gnsilence** [comment]
> 在定期作业页面里选中一条job点击编辑定时任务时，这个接口返回了错误，导致该功能不可用。 ![image](https://user-images.githubusercontent.com/26083509/184295793-62ef7feb-0710-4f81-8cda-4af88f6db2e5.png) 在Hangfire.HttpJob.dll模块中抛出了一个Object reference not set to an instance of an object.异常 ![image](https://user-images.githubusercontent.com/26083509/184296146-48514613-69cd-428c-af2e-8e760257dd7f.png)

使用之前的包，需要手动设置异步io

**Comment by BingboLI** [comment]
Hangfire是1.8,HangfireHttpJob是1.1.2，也需要手动设置异步IO吗？

**Comment by gnsilence** [comment]
如果是在iis下使用，需要手动设置，其他方式下不需要，已经内部设置了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gnsilence/HangfireHttpJob"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月12日(星期五) 下午2:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gnsilence/HangfireHttpJob] 1.1.2中编辑定时任务接口 (Issue #18)





 
Hangfire是1.8,HangfireHttpJob是1.1.2，也需要手动设置异步IO吗？

**Comment by BingboLI** [comment]
我没有在iis下使用，而是在kestrel启动

**Comment by gnsilence** [comment]
你的作业是新创建的，还是以前的任务，最新版可能和历史任务不兼容，还有一种方式可以查看具体的错误，

在你的宿主程序中开启日志，添加&nbsp;"Hangfire": "Information"，如果你使用了log4等日志，就可以在bin目录log下，看到错误日志的详细信息


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gnsilence/HangfireHttpJob"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月12日(星期五) 下午2:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gnsilence/HangfireHttpJob] 1.1.2中编辑定时任务接口 (Issue #18)





 
我没有在iis下使用，而是在kestrel启动

**Comment by BingboLI** [comment]
你好，我下载源码引入调试发现了问题所在。
![image](https://user-images.githubusercontent.com/26083509/184304933-3bea1195-0320-4ead-ab9d-439c107c73b3.png)
在这里我的Job是一个无参的函数调用，当获取不到参数时引发了空对象

**Comment by gnsilence** [comment]
你的job是自己定义的，不是通过页面或者接口添加的吧，目前还不支持这种任务的编辑，后面会考虑加进来


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gnsilence/HangfireHttpJob"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月12日(星期五) 下午3:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gnsilence/HangfireHttpJob] 1.1.2中编辑定时任务接口 (Issue #18)





 
你好，我下载源码引入调试发现了问题所在。
 
 在这里我的Job是一个无参的函数调用，当获取不到参数时引发了空对象

**Comment by BingboLI** [comment]
感谢您的解答，我通过页面新增的Job是没有问题

**Comment by gnsilence** [comment]
你用的nuget包的哪个版本呢，这种情况一般都是没设置异步io




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gnsilence/HangfireHttpJob"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月12日(星期五) 下午2:21
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[gnsilence/HangfireHttpJob] 1.1.2中编辑定时任务接口 (Issue #18)





 
在定期作业页面里选中一条job点击编辑定时任务时，这个接口返回了错误，导致该功能不可用。
 
 在Hangfire.HttpJob.dll模块中抛出了一个Object reference not set to an instance of an object.异常
