### ISSUE TITLE
http如何返回可以让Job进入失败状态？

### ISSUE THREAD

**Issue by BingboLI** [gnsilence/HangfireHttpJob#19]
我在http webapi中处理定时任务，如果有业务逻辑上的错误，我返回500错误是否会让job进入失败状态呢？

**Comment by gnsilence** [comment]
不会进入失败，进入失败只有接口无法访问或者接口访问超时这种情况


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gnsilence/HangfireHttpJob"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月22日(星期一) 下午2:49
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[gnsilence/HangfireHttpJob] http如何返回可以让Job进入失败状态？ (Issue #19)





 
我在http webapi中处理定时任务，如果有业务逻辑上的错误，我返回500错误是否会让job进入失败状态呢？

**Comment by BingboLI** [comment]
可以支持根据返回结果判断失败场景吗？有些业务场景有业务逻辑失败，需要job进入失败，方便管理。

**Comment by gnsilence** [comment]
> 可以支持根据返回结果判断失败场景吗？有些业务场景有业务逻辑失败，需要job进入失败，方便管理。

已经有解决方案能实现这种需求，明天增加了可以发一个版本

**Comment by gnsilence** [comment]
我看下可以实现不


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gnsilence/HangfireHttpJob"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月22日(星期一) 下午3:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gnsilence/HangfireHttpJob] http如何返回可以让Job进入失败状态？ (Issue #19)





 
可以支持根据返回结果判断失败场景吗？有些业务场景有业务逻辑失败，需要job进入失败，方便管理。
