### ISSUE TITLE
Button Not Showing In Dashboard UI

### ISSUE THREAD

**Issue by iamsid** [gnsilence/HangfireHttpJob#2]
Hi.
This is not a bug/issue per se. Its just that I am unable to get the button to show up on the dashboard's UI as shown in the screenshots.
I have referred the sample code also, but no luck.
I am using [this](https://github.com/xavierjefferson/Hangfire.FluentNHibernateStorage) for MySQL storage. Regular Hangfire and its jobs seem to be working fine.
My project is a MVC Web Application.

I don't really know what else to post here for you to understand the problem better, so please ask and help me fix this.

P.S. I found this to be the best place to inform about my issue. If this is not place to do it, please point me in the right direction.

**Comment by gnsilence** [comment]
What's your asp.net core version?
I'll try to write an example with mvc to see if it works properly.
I haven't tried to use it in the 3.0 version of asp.net core.

**Comment by gnsilence** [comment]
> Hi.
> This is not a bug/issue per se. Its just that I am unable to get the button to show up on the dashboard's UI as shown in the screenshots.
> I have referred the sample code also, but no luck.
> I am using this for MySQL storage. Regular Hangfire and its jobs seem to be working fine.
> My project is a MVC Web Application.
> I don't really know what else to post here for you to understand the problem better, so please ask and help me fix this.
> P.S. I found this to be the best place to inform about my issue. If this is not place to do it, please point me in the right direction.

Hi, I have add a MVC with asp.net core 2.2 demo. It uses MySQL as a repository.
You can try and see if it meets your requirements.

**Comment by iamsid** [comment]
Thanks a lot for the update. I will check it asap. 🙂

**Comment by iamsid** [comment]
Hi, thanks for the help. Turns out I was not using .NET Core, and that is a requirement for this.
My project was .Net Framework based, so my bad.
