### ISSUE TITLE
动态添加计划时发生异常

### ISSUE THREAD

**Issue by Radiance-zzg** [gnsilence/HangfireHttpJob#20]
![1661430186856](https://user-images.githubusercontent.com/54875163/186663296-008440a6-6d13-490a-a74d-75a787ed74b3.jpg)

**Comment by Radiance-zzg** [comment]
![image](https://user-images.githubusercontent.com/54875163/186663903-ecab608d-bdea-4bf7-ad52-a2aefcd541ee.png)

**Comment by gnsilence** [comment]
> ![1661430186856](https://user-images.githubusercontent.com/54875163/186663296-008440a6-6d13-490a-a74d-75a787ed74b3.jpg)
运行环境是啥iis还是其他，用的最新的nuget包吗，看样子是异步io未开启或者参数不匹配

**Comment by Radiance-zzg** [comment]
用的是源码里的
![image](https://user-images.githubusercontent.com/54875163/186877639-629ff32e-c54a-4f09-bd10-890d49b0d8f9.png)

**Comment by gnsilence** [comment]
我这里测试没问题，你可以用我给的测试连接进行测试 http://49.233.174.240:8055/job   账号密码都是admin

**Comment by Radiance-zzg** [comment]
找到原因了 已解决
