### ISSUE TITLE
1.1.3版本，我在线新增job时，会覆盖现有的job，而不是新增一个job

### ISSUE THREAD

**Issue by BingboLI** [gnsilence/HangfireHttpJob#22]
我已经创建了一个job，当我创建第二个job时，点击保存没有新的job出现，而是把第一个job给覆盖了

**Comment by gnsilence** [comment]
> 我已经创建了一个job，当我创建第二个job时，点击保存没有新的job出现，而是把第一个job给覆盖了

两个job名称一样吗，目前是如果名称一样会覆盖之前已经存在的

**Comment by BingboLI** [comment]
我的错，我直接复制了第一个job的信息修改。
