### ISSUE TITLE
Redis连接一直报错

### ISSUE THREAD

**Issue by mkc-xuliangjie** [gnsilence/HangfireHttpJob#7]
An unhandled exception occurred while processing the request.
RedisConnectionException: UnableToConnect on 127.0.0.1:6390/Interactive, Initializing, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 2s ago, last-write: 2s ago, unanswered-write: 191439s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.0.513.63329

**Comment by gnsilence** [comment]
应该是redis连接错误,你可以先看看redis可以正常连接吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jason xu"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月4日(星期三) 下午2:36
收件人:&nbsp;"gnsilence/HangfireHttpJob"<HangfireHttpJob@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[gnsilence/HangfireHttpJob] Redis连接一直报错 (#7)




An unhandled exception occurred while processing the request.
 RedisConnectionException: UnableToConnect on 127.0.0.1:6390/Interactive, Initializing, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 2s ago, last-write: 2s ago, unanswered-write: 191439s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.0.513.63329

**Comment by mkc-xuliangjie** [comment]
应该是我自己看错了，谢谢了。
